
package com.sltc.soa.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemoWSService", targetNamespace = "http://soa.sltc.com/", wsdlLocation = "http://localhost:8888/DemoWebService?wsdl")
public class DemoWSService
    extends Service
{

    private final static URL DEMOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEMOWSSERVICE_EXCEPTION;
    private final static QName DEMOWSSERVICE_QNAME = new QName("http://soa.sltc.com/", "DemoWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/DemoWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEMOWSSERVICE_WSDL_LOCATION = url;
        DEMOWSSERVICE_EXCEPTION = e;
    }

    public DemoWSService() {
        super(__getWsdlLocation(), DEMOWSSERVICE_QNAME);
    }

    public DemoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMOWSSERVICE_QNAME, features);
    }

    public DemoWSService(URL wsdlLocation) {
        super(wsdlLocation, DEMOWSSERVICE_QNAME);
    }

    public DemoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMOWSSERVICE_QNAME, features);
    }

    public DemoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DemoWS
     */
    @WebEndpoint(name = "DemoWSPort")
    public DemoWS getDemoWSPort() {
        return super.getPort(new QName("http://soa.sltc.com/", "DemoWSPort"), DemoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoWS
     */
    @WebEndpoint(name = "DemoWSPort")
    public DemoWS getDemoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.sltc.com/", "DemoWSPort"), DemoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMOWSSERVICE_EXCEPTION!= null) {
            throw DEMOWSSERVICE_EXCEPTION;
        }
        return DEMOWSSERVICE_WSDL_LOCATION;
    }

}
