
package com.sltc.soa.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoWS", targetNamespace = "http://soa.sltc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transfer", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.TransferResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/transferRequest", output = "http://soa.sltc.com/DemoWS/transferResponse")
    public int transfer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkUserAccount", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CheckUserAccount")
    @ResponseWrapper(localName = "checkUserAccountResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CheckUserAccountResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/checkUserAccountRequest", output = "http://soa.sltc.com/DemoWS/checkUserAccountResponse")
    public boolean checkUserAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountNumber", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.GetAccountNumber")
    @ResponseWrapper(localName = "getAccountNumberResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.GetAccountNumberResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/getAccountNumberRequest", output = "http://soa.sltc.com/DemoWS/getAccountNumberResponse")
    public String getAccountNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewClient", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.AddNewClient")
    @ResponseWrapper(localName = "addNewClientResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.AddNewClientResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/addNewClientRequest", output = "http://soa.sltc.com/DemoWS/addNewClientResponse")
    public int addNewClient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        float arg5);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.WithdrawResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/withdrawRequest", output = "http://soa.sltc.com/DemoWS/withdrawResponse")
    public int withdraw(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkNIC", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CheckNIC")
    @ResponseWrapper(localName = "checkNICResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CheckNICResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/checkNICRequest", output = "http://soa.sltc.com/DemoWS/checkNICResponse")
    public boolean checkNIC(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deposit", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.DepositResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/depositRequest", output = "http://soa.sltc.com/DemoWS/depositResponse")
    public int deposit(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.GetBalanceResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/getBalanceRequest", output = "http://soa.sltc.com/DemoWS/getBalanceResponse")
    public float getBalance(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authoriseUser", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.AuthoriseUser")
    @ResponseWrapper(localName = "authoriseUserResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.AuthoriseUserResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/authoriseUserRequest", output = "http://soa.sltc.com/DemoWS/authoriseUserResponse")
    public int authoriseUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkUserName", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CheckUserName")
    @ResponseWrapper(localName = "checkUserNameResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.CheckUserNameResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/checkUserNameRequest", output = "http://soa.sltc.com/DemoWS/checkUserNameResponse")
    public boolean checkUserName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
